# -*- coding: utf-8 -*-
"""EMIpredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vyi3LNqmCcrQFBFuiGbiWLbe4zc4hKnm

## 1. Environment Setup and Data Loading

First, let's install the required libraries. This includes `pandas` for data manipulation, `scikit-learn` for machine learning, `mlflow` for experiment tracking, and `streamlit` for the web application (though we won't fully build the Streamlit app in Colab, we'll set up its dependencies).
"""

pip install pandas numpy scikit-learn mlflow streamlit

"""Now, let's import the necessary libraries."""

import pandas as pd
import numpy as np
import sklearn
import mlflow
print('Libraries imported successfully!')

"""Since no specific dataset was provided, I will generate a synthetic dataset with approximately 400,000 records and 22 financial and demographic variables, including target variables for EMI eligibility (classification) and maximum EMI amount (regression). This will allow us to simulate the project's requirements.

### Synthetic Data Generation
"""

# Reload the dataset to start fresh
df = pd.read_csv('/content/emi_prediction_dataset.csv')

# Identify columns that should be numeric but are object type
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['monthly_salary'] = pd.to_numeric(df['monthly_salary'], errors='coerce')
df['bank_balance'] = pd.to_numeric(df['bank_balance'], errors='coerce')

# Convert 'existing_loans' from 'Yes'/'No' to 1/0 using .replace()
df['existing_loans'] = df['existing_loans'].replace({'Yes': 1, 'No': 0})

# Convert 'emi_eligibility' to numerical:
# Map 'Eligible' to 1, and 'Not_Eligible'/'High_Risk' to 0
df['emi_eligibility'] = df['emi_eligibility'].replace({'Eligible': 1, 'Not_Eligible': 0, 'High_Risk': 0})

print('\nData types after initial conversion:')
display(df.info())

print('\nMissing values after initial conversion and target mapping:')
display(df.isnull().sum())

# Drop rows where 'emi_eligibility' is still NaN (should be none after improved mapping), as it's a target variable
df.dropna(subset=['emi_eligibility'], inplace=True)

# Handle remaining missing values:
# Impute numerical columns with their median
for col in ['age', 'monthly_salary', 'monthly_rent', 'credit_score', 'bank_balance', 'emergency_fund', 'existing_loans']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())

# Impute categorical columns with their mode
for col in ['education']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

# Convert 'emi_eligibility' to integer type after dropping NaNs and imputation
df['emi_eligibility'] = df['emi_eligibility'].astype(int)

print('\nMissing values after imputation and target row drop:')
display(df.isnull().sum())

print('\nDescriptive statistics for numerical features:')
display(df.describe())

print('\nFirst few rows after preprocessing:')
display(df.head())

# Identify categorical columns for one-hot encoding
categorical_cols = df.select_dtypes(include='object').columns
print(f"Categorical columns identified for one-hot encoding: {list(categorical_cols)}")

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print(f"\nShape of DataFrame after one-hot encoding: {df_encoded.shape}")
display(df_encoded.head())

# Separate features (X) and target variables (y)
X = df_encoded.drop(['emi_eligibility', 'max_monthly_emi'], axis=1)
y_eligible = df_encoded['emi_eligibility'] # Classification target
y_amount = df_encoded['max_monthly_emi'] # Regression target

print(f"\nShape of features (X): {X.shape}")
print(f"Shape of EMI eligibility target (y_eligible): {y_eligible.shape}")
print(f"Shape of Max EMI amount target (y_amount): {y_amount.shape}")

"""### 3.1 EMI Eligibility Prediction (Classification Model)

First, let's split our data into training and testing sets for the classification task. We'll use a `LogisticRegression` model as a baseline for EMI eligibility prediction.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Split data for classification
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X, y_eligible, test_size=0.2, random_state=42)

print("Data split for Classification:")
print(f"X_train_cls shape: {X_train_cls.shape}")
print(f"y_train_cls shape: {y_train_cls.shape}")
print(f"X_test_cls shape: {X_test_cls.shape}")
print(f"y_test_cls shape: {y_test_cls.shape}")

# Initialize and train Logistic Regression model
cls_model = LogisticRegression(random_state=42, solver='liblinear', C=0.1, max_iter=1000)

# Start MLflow run for classification model
with mlflow.start_run(run_name="EMI_Eligibility_Logistic_Regression") as run:
    mlflow.log_param("model_type", "LogisticRegression")
    mlflow.log_param("solver", "liblinear")
    mlflow.log_param("C", 0.1)
    mlflow.log_param("max_iter", 1000)

    cls_model.fit(X_train_cls, y_train_cls)
    y_pred_cls = cls_model.predict(X_test_cls)
    y_pred_proba_cls = cls_model.predict_proba(X_test_cls)[:, 1]

    # Evaluate classification model
    accuracy = accuracy_score(y_test_cls, y_pred_cls)
    precision = precision_score(y_test_cls, y_pred_cls)
    recall = recall_score(y_test_cls, y_pred_cls)
    f1 = f1_score(y_test_cls, y_pred_cls)
    roc_auc = roc_auc_score(y_test_cls, y_pred_proba_cls)

    print(f"\nClassification Model Metrics:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"ROC AUC Score: {roc_auc:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1_score", f1)
    mlflow.log_metric("roc_auc_score", roc_auc)

    # Log the model
    mlflow.sklearn.log_model(cls_model, "logistic_regression_model")
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""### 3.2 Maximum EMI Amount Prediction (Regression Model)

Now, let's prepare the data and train a regression model to predict the `max_monthly_emi` amount. We'll start with a `LinearRegression` model as a baseline and also log its metrics to MLflow.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Split data for regression
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_amount, test_size=0.2, random_state=42)

print("Data split for Regression:")
print(f"X_train_reg shape: {X_train_reg.shape}")
print(f"y_train_reg shape: {y_train_reg.shape}")
print(f"X_test_reg shape: {X_test_reg.shape}")
print(f"y_test_reg shape: {y_test_reg.shape}")

# Initialize and train Linear Regression model
reg_model = LinearRegression()

# Start MLflow run for regression model
with mlflow.start_run(run_name="EMI_Amount_Linear_Regression") as run:
    mlflow.log_param("model_type", "LinearRegression")

    reg_model.fit(X_train_reg, y_train_reg)
    y_pred_reg = reg_model.predict(X_test_reg)

    # Evaluate regression model
    mse = mean_squared_error(y_test_reg, y_pred_reg)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test_reg, y_pred_reg)
    r2 = r2_score(y_test_reg, y_pred_reg)

    print(f"\nRegression Model Metrics:")
    print(f"Mean Squared Error (MSE): {mse:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
    print(f"Mean Absolute Error (MAE): {mae:.4f}")
    print(f"R2 Score: {r2:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("mse", mse)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("mae", mae)
    mlflow.log_metric("r2_score", r2)

    # Log the model
    mlflow.sklearn.log_model(reg_model, "linear_regression_model")
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""### 3.2.1 Random Forest Regressor for Maximum EMI Amount Prediction

Now, let's train a `RandomForestRegressor` and track its performance using MLflow. This ensemble model is known for its robustness and accuracy.
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

# Initialize and train Random Forest Regressor model
# Using a small number of estimators and max_depth for quicker execution in Colab
rf_reg_model = RandomForestRegressor(n_estimators=50, max_depth=10, random_state=42, n_jobs=-1)

# Start MLflow run for Random Forest regression model
with mlflow.start_run(run_name="EMI_Amount_Random_Forest_Regression") as run:
    mlflow.log_param("model_type", "RandomForestRegressor")
    mlflow.log_param("n_estimators", 50)
    mlflow.log_param("max_depth", 10)

    rf_reg_model.fit(X_train_reg, y_train_reg)
    y_pred_rf_reg = rf_reg_model.predict(X_test_reg)

    # Evaluate regression model
    mse_rf = mean_squared_error(y_test_reg, y_pred_rf_reg)
    rmse_rf = np.sqrt(mse_rf)
    mae_rf = mean_absolute_error(y_test_reg, y_pred_rf_reg)
    r2_rf = r2_score(y_test_reg, y_pred_rf_reg)

    print(f"\nRandom Forest Regression Model Metrics:")
    print(f"Mean Squared Error (MSE): {mse_rf:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse_rf:.4f}")
    print(f"Mean Absolute Error (MAE): {mae_rf:.4f}")
    print(f"R2 Score: {r2_rf:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("mse", mse_rf)
    mlflow.log_metric("rmse", rmse_rf)
    mlflow.log_metric("mae", mae_rf)
    mlflow.log_metric("r2_score", r2_rf)

    # Log the model
    mlflow.sklearn.log_model(rf_reg_model, "random_forest_regressor_model")
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""### 3.2.2 XGBoost Regressor for Maximum EMI Amount Prediction

Finally, for the regression task, let's train an `XGBoostRegressor`. XGBoost is known for its high performance and is often a strong contender in various machine learning competitions. We'll track its performance with MLflow.
"""

import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

# Initialize and train XGBoost Regressor model
# Using a small number of estimators and max_depth for quicker execution in Colab
xgb_reg_model = xgb.XGBRegressor(n_estimators=100, max_depth=5, random_state=42, n_jobs=-1)

# Start MLflow run for XGBoost regression model
with mlflow.start_run(run_name="EMI_Amount_XGBoost_Regression") as run:
    mlflow.log_param("model_type", "XGBoostRegressor")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 5)

    xgb_reg_model.fit(X_train_reg, y_train_reg)
    y_pred_xgb_reg = xgb_reg_model.predict(X_test_reg)

    # Evaluate regression model
    mse_xgb = mean_squared_error(y_test_reg, y_pred_xgb_reg)
    rmse_xgb = np.sqrt(mse_xgb)
    mae_xgb = mean_absolute_error(y_test_reg, y_pred_xgb_reg)
    r2_xgb = r2_score(y_test_reg, y_pred_xgb_reg)

    print(f"\nXGBoost Regression Model Metrics:")
    print(f"Mean Squared Error (MSE): {mse_xgb:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse_xgb:.4f}")
    print(f"Mean Absolute Error (MAE): {mae_xgb:.4f}")
    print(f"R2 Score: {r2_xgb:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("mse", mse_xgb)
    mlflow.log_metric("rmse", rmse_xgb)
    mlflow.log_metric("mae", mae_xgb)
    mlflow.log_metric("r2_score", r2_xgb)

    # Log the model, explicitly trusting xgboost types
    mlflow.sklearn.log_model(xgb_reg_model, "xgboost_regressor_model", skops_trusted_types=['xgboost.core.Booster', 'xgboost.sklearn.XGBRegressor'])
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""### 3.1.1 Random Forest Classifier for EMI Eligibility Prediction

Let's now train a `RandomForestClassifier` for the EMI eligibility prediction. This model is generally robust and can provide insights into feature importance.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Initialize and train Random Forest Classifier model
# Using a small number of estimators and max_depth for quicker execution in Colab
rf_cls_model = RandomForestClassifier(n_estimators=50, max_depth=10, random_state=42, n_jobs=-1)

# Start MLflow run for Random Forest classification model
with mlflow.start_run(run_name="EMI_Eligibility_Random_Forest_Classifier") as run:
    mlflow.log_param("model_type", "RandomForestClassifier")
    mlflow.log_param("n_estimators", 50)
    mlflow.log_param("max_depth", 10)

    rf_cls_model.fit(X_train_cls, y_train_cls)
    y_pred_rf_cls = rf_cls_model.predict(X_test_cls)
    y_pred_proba_rf_cls = rf_cls_model.predict_proba(X_test_cls)[:, 1]

    # Evaluate classification model
    accuracy_rf_cls = accuracy_score(y_test_cls, y_pred_rf_cls)
    precision_rf_cls = precision_score(y_test_cls, y_pred_rf_cls)
    recall_rf_cls = recall_score(y_test_cls, y_pred_rf_cls)
    f1_rf_cls = f1_score(y_test_cls, y_pred_rf_cls)
    roc_auc_rf_cls = roc_auc_score(y_test_cls, y_pred_proba_rf_cls)

    print(f"\nRandom Forest Classification Model Metrics:")
    print(f"Accuracy: {accuracy_rf_cls:.4f}")
    print(f"Precision: {precision_rf_cls:.4f}")
    print(f"Recall: {recall_rf_cls:.4f}")
    print(f"F1-Score: {f1_rf_cls:.4f}")
    print(f"ROC AUC Score: {roc_auc_rf_cls:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("accuracy", accuracy_rf_cls)
    mlflow.log_metric("precision", precision_rf_cls)
    mlflow.log_metric("recall", recall_rf_cls)
    mlflow.log_metric("f1_score", f1_rf_cls)
    mlflow.log_metric("roc_auc_score", roc_auc_rf_cls)

    # Log the model
    mlflow.sklearn.log_model(rf_cls_model, "random_forest_classifier_model")
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""### 3.1.2 XGBoost Classifier for EMI Eligibility Prediction

To complete the classification model development, let's train an `XGBoostClassifier`. XGBoost is a powerful gradient boosting framework known for its efficiency and accuracy.
"""

import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Initialize and train XGBoost Classifier model
# Using a small number of estimators and max_depth for quicker execution in Colab
xgb_cls_model = xgb.XGBClassifier(n_estimators=100, max_depth=5, random_state=42, use_label_encoder=False, eval_metric='logloss', n_jobs=-1)

# Start MLflow run for XGBoost classification model
with mlflow.start_run(run_name="EMI_Eligibility_XGBoost_Classifier") as run:
    mlflow.log_param("model_type", "XGBoostClassifier")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 5)
    mlflow.log_param("eval_metric", "logloss")

    xgb_cls_model.fit(X_train_cls, y_train_cls)
    y_pred_xgb_cls = xgb_cls_model.predict(X_test_cls)
    y_pred_proba_xgb_cls = xgb_cls_model.predict_proba(X_test_cls)[:, 1]

    # Evaluate classification model
    accuracy_xgb_cls = accuracy_score(y_test_cls, y_pred_xgb_cls)
    precision_xgb_cls = precision_score(y_test_cls, y_pred_xgb_cls)
    recall_xgb_cls = recall_score(y_test_cls, y_pred_xgb_cls)
    f1_xgb_cls = f1_score(y_test_cls, y_pred_xgb_cls)
    roc_auc_xgb_cls = roc_auc_score(y_test_cls, y_pred_proba_xgb_cls)

    print(f"\nXGBoost Classification Model Metrics:")
    print(f"Accuracy: {accuracy_xgb_cls:.4f}")
    print(f"Precision: {precision_xgb_cls:.4f}")
    print(f"Recall: {recall_xgb_cls:.4f}")
    print(f"F1-Score: {f1_xgb_cls:.4f}")
    print(f"ROC AUC Score: {roc_auc_xgb_cls:.4f}")

    # Log metrics to MLflow
    mlflow.log_metric("accuracy", accuracy_xgb_cls)
    mlflow.log_metric("precision", precision_xgb_cls)
    mlflow.log_metric("recall", recall_xgb_cls)
    mlflow.log_metric("f1_score", f1_xgb_cls)
    mlflow.log_metric("roc_auc_score", roc_auc_xgb_cls)

    # Log the model, explicitly trusting xgboost types
    mlflow.sklearn.log_model(xgb_cls_model, "xgboost_classifier_model", skops_trusted_types=['xgboost.core.Booster', 'xgboost.sklearn.XGBClassifier'])
    print(f"MLflow Run ID: {run.info.run_id}")
    print(f"MLflow Artifact URI: {mlflow.get_artifact_uri()}")

"""## 5. Model Selection and MLflow Integration

Now that we have trained and logged multiple models for both EMI eligibility classification and maximum EMI amount regression, we can use the MLflow UI to compare their performance and select the best models for deployment.

### Launch MLflow UI

To view the MLflow UI, run the following command in a new terminal in Google Colab (Go to: `Terminal` -> `New terminal`).

```bash
mlflow ui
```

Once the MLflow UI is running, you can access it by clicking on the `Web Preview` button that appears in the Colab output or by navigating to the URL it provides (usually `http://127.0.0.1:5000` or similar).

In the MLflow UI, you will be able to:
*   **Compare Runs:** Select multiple runs and compare their metrics and parameters side-by-side.
*   **Filter and Search:** Filter runs based on metric values, parameters, or tags.
*   **View Artifacts:** Inspect the logged models, plots, and other artifacts for each run.

After reviewing the models, we will identify the best performing classification and regression models based on the defined evaluation metrics.

### 5.1 Model Selection

After reviewing the MLflow UI, we can identify the best-performing models for each task:

**For EMI Eligibility Prediction (Classification):**
*   **XGBoost Classifier** demonstrated the highest performance across key metrics like Accuracy (0.9755), Precision (0.9518), Recall (0.9139), F1-Score (0.9324), and ROC AUC (0.9966). This model is robust and suitable for identifying EMI eligibility with high confidence.

**For Maximum EMI Amount Prediction (Regression):**
*   **XGBoost Regressor** also showed superior performance with the lowest RMSE (1306.37) and MAE (872.29), and the highest R2 Score (0.9711). This model provides accurate predictions for the maximum EMI amount.

### 5.2 Implement Model Registry

Now, let's register the selected best models (XGBoost Classifier and XGBoost Regressor) in the MLflow Model Registry. This allows us to version our models and manage their lifecycle for production deployment.
"""

import mlflow
from mlflow.tracking import MlflowClient

# Initialize MLflow Client
client = MlflowClient()

# Define model names for registration
cls_model_name = "EMI_Eligibility_XGBoost_Classifier"
# Corrected: The run name for the regression model was 'EMI_Amount_XGBoost_Regression'
reg_model_name = "EMI_Amount_XGBoost_Regression"

# Find the run ID for the best classification model (XGBoost Classifier)
# Assuming the latest run for 'EMI_Eligibility_XGBoost_Classifier' is the one we want to register.
# In a real scenario, you would select based on the best metric from MLflow UI comparison.
cls_runs = client.search_runs(
    experiment_ids=client.get_experiment_by_name("Default").experiment_id,
    filter_string=f"tags.mlflow.runName = '{cls_model_name}'",
    order_by=["metrics.accuracy DESC"], # Order by accuracy to pick the best if multiple runs exist
    max_results=1
)

if cls_runs:
    best_cls_run_id = cls_runs[0].info.run_id
    print(f"Found best classification run ID: {best_cls_run_id}")
    # Register the model
    registered_cls_model = mlflow.register_model(
        model_uri=f"runs:/{best_cls_run_id}/xgboost_classifier_model",
        name=cls_model_name
    )
    print(f"Registered Classification Model: {registered_cls_model.name}, Version: {registered_cls_model.version}")
else:
    print(f"Could not find a run for classification model: {cls_model_name}")

# Find the run ID for the best regression model (XGBoost Regressor)
# Assuming the latest run for 'EMI_Amount_XGBoost_Regression' is the one we want to register.
reg_runs = client.search_runs(
    experiment_ids=client.get_experiment_by_name("Default").experiment_id,
    filter_string=f"tags.mlflow.runName = '{reg_model_name}'",
    order_by=["metrics.rmse ASC"], # Order by RMSE to pick the best (lower is better)
    max_results=1
)

if reg_runs:
    best_reg_run_id = reg_runs[0].info.run_id
    print(f"Found best regression run ID: {best_reg_run_id}")
    # Register the model
    registered_reg_model = mlflow.register_model(
        model_uri=f"runs:/{best_reg_run_id}/xgboost_regressor_model",
        name=reg_model_name # Use the correct model name for registration
    )
    print(f"Registered Regression Model: {registered_reg_model.name}, Version: {registered_reg_model.version}")
else:
    print(f"Could not find a run for regression model: {reg_model_name}")

"""## 6. Streamlit Application Development

Now, we'll develop the Streamlit web application to provide an interactive interface for EMI prediction, data exploration, and model monitoring. We will create a multi-page application to organize different functionalities.

### 6.1 Create `app.py` for the Streamlit Application

We'll start by creating the main `app.py` file for our Streamlit application. This file will serve as the entry point and manage the navigation between different pages. We'll use `%%writefile` magic command to create this file in the Colab environment.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import mlflow
# from mlflow.tracking import MlflowClient
# 
# # --- Page Configuration ---
# st.set_page_config(
#     page_title="EMIPredict AI - Financial Risk Assessment",
#     page_icon="🏦",
#     layout="wide"
# )
# 
# # --- MLflow Configuration ---
# # Assuming MLflow tracking server is running locally in Colab
# mlflow.set_tracking_uri("file:///content/mlruns")
# client = MlflowClient()
# 
# # --- Helper function to load registered models ---
# @st.cache_resource
# def load_model(model_name):
#     try:
#         # Get the latest version of the model from MLflow Model Registry
#         model_version = client.get_latest_versions(model_name, stages=["None"])[0].version
#         model_uri = f"models:/{model_name}/{model_version}"
#         model = mlflow.pyfunc.load_model(model_uri)
#         return model
#     except Exception as e:
#         st.error(f"Error loading model {model_name}: {e}")
#         return None
# 
# # Load the best classification and regression models
# cls_model_name = "EMI_Eligibility_XGBoost_Classifier"
# reg_model_name = "EMI_Amount_XGBoost_Regression"
# 
# cls_model = load_model(cls_model_name)
# reg_model = load_model(reg_model_name)
# 
# # --- Main App Structure ---
# st.sidebar.title("Navigation")
# selection = st.sidebar.radio("Go to",
#                             ["Home",
#                              "EMI Prediction",
#                              "Data Exploration",
#                              "Model Monitoring",
#                              "Admin Interface"],
#                             index=0)
# 
# # --- Home Page ---
# if selection == "Home":
#     st.title("🏡 Welcome to EMIPredict AI")
#     st.markdown("""
#     This platform provides a comprehensive financial risk assessment for EMI prediction.
#     It integrates machine learning models with MLflow experiment tracking to offer
#     real-time EMI eligibility and amount predictions, interactive data exploration,
#     and robust model monitoring.
# 
#     **Key Features:**
#     - **EMI Prediction:** Real-time classification of EMI eligibility and regression for maximum EMI amount.
#     - **Data Exploration:** Interactive visualizations and statistical summaries of the dataset.
#     - **Model Monitoring:** Track model performance and experiment results via MLflow dashboard.
#     - **Admin Interface:** Manage and update the underlying dataset.
#     """)
# 
#     st.image("https://images.unsplash.com/photo-1579621970563-cd789438078d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", use_column_width=True)
# 
# # --- EMI Prediction Page ---
# elif selection == "EMI Prediction":
#     st.title("📊 EMI Prediction")
#     st.markdown("Enter customer details to get real-time EMI eligibility and maximum EMI amount predictions.")
# 
#     if cls_model and reg_model:
#         st.success("Models loaded successfully!")
#         # Placeholder for prediction input forms and display results
#         st.subheader("Customer Input Form (Placeholder)")
#         # Example input (you would create actual input widgets here)
#         st.write("Here you would add input widgets for features like age, monthly_salary, etc.")
#         # Example prediction call
#         # if st.button("Predict EMI"):
#         #     dummy_input = pd.DataFrame([np.random.rand(cls_model.n_features_in_)] , columns=cls_model.feature_names_in_)
#         #     eligibility_prediction = cls_model.predict(dummy_input)
#         #     amount_prediction = reg_model.predict(dummy_input)
#         #     st.write(f"EMI Eligibility: {eligibility_prediction[0]}")
#         #     st.write(f"Max EMI Amount: {amount_prediction[0]:.2f}")
#     else:
#         st.warning("Models could not be loaded. Please ensure they are registered in MLflow.")
# 
# # --- Data Exploration Page ---
# elif selection == "Data Exploration":
#     st.title("🔍 Data Exploration")
#     st.markdown("Explore the underlying dataset with interactive visualizations.")
#     # Placeholder for data loading and visualization
#     st.write("Here you would load the dataset and add interactive charts/tables using libraries like Plotly or Altair.")
# 
# # --- Model Monitoring Page ---
# elif selection == "Model Monitoring":
#     st.title("📈 Model Monitoring & MLflow Dashboard")
#     st.markdown("Monitor model performance over time and access the MLflow experiment tracking dashboard.")
#     # Placeholder for MLflow UI embedding or links
#     st.write("You can embed the MLflow UI here or provide a direct link. For now, access the MLflow UI separately.")
#     st.code("mlflow ui")
# 
# # --- Admin Interface Page ---
# elif selection == "Admin Interface":
#     st.title("⚙️ Admin Interface")
#     st.markdown("Manage data, train new models, and update configurations.")
#     # Placeholder for CRUD operations
#     st.write("This section would include functionalities for data upload, editing, deletion, and potentially re-training models.")
#

"""### 6.2 Run the Streamlit Application

To run the Streamlit application within Google Colab, you need to use `!streamlit run app.py` command. Since Streamlit runs as a server, you'll need to use `nohup` and `&` to run it in the background, and `npx localtunnel` to expose the port.

1.  **Run Streamlit in the background:**
    ```bash
    nohup streamlit run app.py --server.port 8051 --server.enableCORS false --server.enableXsrfProtection false > app.log 2>&1 &
    ```
2.  **Expose the port using `localtunnel`:**
    ```bash
    npx localtunnel --port 8051
    ```

Run these commands in separate terminal tabs in Colab (Go to: `Terminal` -> `New terminal`). After running the `localtunnel` command, it will provide a public URL that you can open in your browser to access the Streamlit application.
"""

!streamlit run app.py